`Pipfile.lock`に`comtypes`を含んでいるかどうかで`setuptools`や`wheel`のバージョンを変更する分岐を追加
fierte-product-development/Setups pull request #2
Opened 2022-01-26 07:58 UTC by junkmd

#1 の対応です。

`Pipfile.lock`に`comtypes`を含んでいれば、`setuptools`や`wheel`のバージョンを変更した上で仮想環境が作られるように分岐を作成しました。

- `comtypes`が指定されていない場合にはローカルの`pipenv`の仕様に依存したバージョンが使用されます。

なぜこのバージョンなのかは[`comtypes`issue](https://github.com/enthought/comtypes/issues/180#issuecomment-1009586423)を参照してください。

2022-01-26 07:58 UTC, junkmd commented
@hiro-torii 
1次レビューをお願いします。

2022-01-26 08:20 UTC, hiro-torii approved these changes
対応ありがとうございます！
いくつか指摘あります

2022-01-26 08:20 UTC, hiro-torii commented on setup_python.py
> +    _popen('pipenv', 'run', 'python', '-m', 'pip', 'list')
ここのpip listはどういう意図で行っていますか？

2022-01-26 08:20 UTC, hiro-torii commented on setup_python.py
> +from typing import Any
Anyはコード中で参照されていないように見えます

2022-01-26 08:20 UTC, hiro-torii commented on setup_python.py
> +    """`pipenv update/install ...`を使用せず、仮想環境の`pip`を直接使ってライブラリのバージョンを変更します。
「仮想環境の`pip`を直接使ってライブラリのバージョンを変更します。」ここだけで大丈夫かと思います

2022-01-26 08:20 UTC, hiro-torii commented on setup_python.py
> +        `Pipfile.lock`で管理できない、環境作成時に用いるセットアップ系ライブラリを指定するための関数。
「環境作成時に用いるセットアップ系ライブラリを指定する」
⇒「環境作成時に用いるライブラリのバージョンを指定する」　の方が個人的にわかりやすい気がしました。

2022-01-26 08:20 UTC, hiro-torii requested changes
すみません、、、間違えてapproveしちゃってました…

2022-01-26 09:11 UTC, junkmd commented on setup_python.py
> +    _popen('pipenv', 'run', 'python', '-m', 'pip', 'list')
`.venv`フォルダが実行環境にない状態で`pipenv run コマンドなら何でもいい`で、`.venv`が作られるためです。

`pip list`なのは
- 必ず環境に`pip`はある
- デフォルトの`wheel`, `setuptools`のバージョンがなにかをついでに確認できる
- ライブラリをインストールする前なので表示される行数は全部で5行程度
- 仮想環境が立てられた時点でその内容が表示されるのは自然な流れとして許容できるのでは
- 空`py`ファイルを作ってrunさせてもいいのですが、そのためにファイルを1つ増やすのは冗長

ということで使っています。

2022-01-26 09:39 UTC, junkmd commented on setup_python.py
> +    _popen('pipenv', 'run', 'python', '-m', 'pip', 'list')
実行時にコマンドプロンプトに流れるのは下記のような内容です。
```
Active code page: 65001

Python環境のセットアップを行います…

$ python -m pip install --upgrade pip
Requirement already satisfied: pip in c:\users\blah\appdata\local\programs\python\python38\lib\site-packages (21.3.1)

$ pip install pipenv
Requirement already satisfied: pipenv in c:\users\blah\appdata\local\programs\python\python38\lib\site-packages (2018.11.26)
Requirement already satisfied: pip>=9.0.1 in c:\users\blah\appdata\local\programs\python\python38\lib\site-packages (from pipenv) (21.3.1)
Requirement already satisfied: certifi in c:\users\blah\appdata\local\programs\python\python38\lib\site-packages (from pipenv) (2020.4.5.1)
Requirement already satisfied: virtualenv-clone>=0.2.5 in c:\users\blah\appdata\local\programs\python\python38\lib\site-packages (from pipenv) (0.5.4)
Requirement already satisfied: virtualenv in c:\users\blah\appdata\local\programs\python\python38\lib\site-packages (from pipenv) (20.0.18)
Requirement already satisfied: setuptools>=36.2.1 in c:\users\blah\appdata\local\programs\python\python38\lib\site-packages (from pipenv) (41.2.0)
Requirement already satisfied: six<2,>=1.9.0 in c:\users\blah\appdata\local\programs\python\python38\lib\site-packages (from virtualenv->pipenv) (1.14.0)
Requirement already satisfied: appdirs<2,>=1.4.3 in c:\users\blah\appdata\local\programs\python\python38\lib\site-packages (from virtualenv->pipenv) (1.4.3)
Requirement already satisfied: distlib<1,>=0.3.0 in c:\users\blah\appdata\local\programs\python\python38\lib\site-packages (from virtualenv->pipenv) (0.3.0)
Requirement already satisfied: filelock<4,>=3.0.0 in c:\users\blah\appdata\local\programs\python\python38\lib\site-packages (from virtualenv->pipenv) (3.0.12)

仮想環境が既に存在します。
C:\myrepo\.venv
このフォルダを消去して新しく環境を作成しますか？(y/n): y
$ pipenv --rm
Removing virtualenv (C:\myrepo\.venv)…

[    ] Running...
...
[  ==] Running...

仮想環境を作成します。
`.venv`フォルダを作成して`python.exe`や環境セットアップ系ライブラリをインストールします。
$ pipenv run python -m pip list
Creating a virtualenv for this project…
Pipfile: C:\myrepo\Pipfile
Using C:/Users/blah/AppData/Local/Programs/Python/Python39/python.exe (3.9.1) to create virtualenv…

[    ] Creating virtual environment...
...
[    ] Creating virtual environment...created virtual environment CPython3.9.1.final.0-64 in 5558ms

  creator CPython3Windows(dest=C:\myrepo\.venv, clear=False, global=False)

  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=C:\Users\blah\AppData\Local\pypa\virtualenv\seed-app-data\v1.0.1)

  activators BashActivator,BatchActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

Successfully created virtual environment!
Virtualenv location: C:\myrepo\.venv
Loading .env environment variables…
Package    Version
---------- -------
pip        20.0.2
setuptools 46.1.3
wheel      0.34.2

`setuptools`のバージョンを57.0.0に変更します。
$ pipenv run python -m pip uninstall -y setuptools
Loading .env environment variables…
Found existing installation: setuptools 46.1.3
Uninstalling setuptools-46.1.3:
  Successfully uninstalled setuptools-46.1.3

$ pipenv run python -m pip install setuptools==57.0.0
Loading .env environment variables…
Collecting setuptools==57.0.0
  Using cached setuptools-57.0.0-py3-none-any.whl (821 kB)
Installing collected packages: setuptools
Successfully installed setuptools-57.0.0

`wheel`のバージョンを0.36.2に変更します。
$ pipenv run python -m pip uninstall -y wheel
Loading .env environment variables…
Found existing installation: wheel 0.34.2
Uninstalling wheel-0.34.2:
  Successfully uninstalled wheel-0.34.2

$ pipenv run python -m pip install wheel==0.36.2
Loading .env environment variables…
Collecting wheel==0.36.2
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel
Successfully installed wheel-0.36.2

`.venv`フォルダに`Pipfile.lock`で指定されているライブラリをインストールします。
$ pipenv sync --dev
Installing dependencies from Pipfile.lock (932c51)…
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
All dependencies are now up-to-date!

仮想環境の作成が完了しました。
```

2022-01-26 09:42 UTC, junkmd commented
@hiro-torii 
指摘いただいた点は直しました。
宜しくお願い致します。

2022-01-26 09:50 UTC, hiro-torii requested changes

2022-01-26 09:50 UTC, hiro-torii commented on setup_python.py
> +    _popen('pipenv', 'run', 'python', '-m', 'pip', 'list')
ありがとうございます！意図はわかりました。
ただ，それをコード上で上手く伝える必要があるとは思います。

96行目のprintは削って97, 98行目のコメントも以下ぐらいでどうですか？
~~~
# 事前に`.venv`フォルダが必要なため、`pip run`で任意のコマンド(今回は`pip list`)を実行。
~~~

2022-01-26 10:01 UTC, junkmd commented
@hiro-torii 
`pipenv sync ...`前の`pipenv run ...`部分も修正しました。

宜しくお願いします。

2022-01-26 10:24 UTC, hiro-torii approved these changes

2022-01-26 10:24 UTC, hiro-torii commented
@y-kanai06 二次レビューお願いします。

2022-01-27 01:19 UTC, y-kanai06 approved these changes

2022-01-27 01:22 UTC, merged